version: "3.9"
services:
  database:
    image: "postgres:14.5"
    container_name: mbti_postgres
    restart: always
    env_file:
      - database/.env
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

